version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: castor_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: castor_db
      MYSQL_USER: castor_user
      MYSQL_PASSWORD: castor_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: 